[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
instant = { version = "0.1", features = ["wasm-bindgen"] }
eframe = "0.33.3"
rand = "0.9.2"
getrandom = { version = "0.3", features = ["wasm_js"] }
